In [2]:
# for installing libraries
!python -m pip install numpy


[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np
# numpy provides datatypes
## numpy.nd .array


In [5]:
a = np. array([3,8,2,67,45])
a

array([ 3,  8,  2, 67, 45])

In [8]:
type(a)

numpy.ndarray

In [6]:
print(a.shape)
print(a.size)
print(a.dtype)

(5,)
5
int32


In [7]:
len(a)

5

In [13]:
def show_Array(arr):
    print('type',type(arr))
    print('Shape',arr.shape)
    print('Size',arr.size)
    print('DType',arr.dtype)
    print('Length',len(arr))
    print(arr.ndim)
    



In [10]:
# 10  11   13   14
# 45   6    9   28
#34    45    23  67
b = np.array([[10,11,13,14],[45,6,9,28],[34,45,23,67]])
show_Array(b)

type <class 'numpy.ndarray'>
Shape (3, 4)
Size 12
DType int32
Length 3


In [51]:
c = np.array([[[10,100],[11,110],[13,45],[13,14]],[[45,67],[56,6],[67,9],
              [54,28]],[[34,78],[23,45],[56,23],[78,67]]])
show_Array(c)

type <class 'numpy.ndarray'>
Shape (3, 4, 2)
Size 24
DType int32
Length 3
3


In [49]:
b

array([[10, 11, 13, 14],
       [45,  6,  9, 28],
       [34, 45, 23, 67]])

In [12]:
#Array operations
##1.Item acessing : Subscripting, Slicing
##2.Item Assigment
##3.Item Deletion
##4. Arithmatic

In [31]:
# Item Acessing
#b
#b[0][0:]
#b[1:][0]
# subscripting[ist,2nd ,third,.....,nth dim]
#subscripting[ist:ist end: stepsize, 2nd, 3rd,....,nth dim]
b[0][0]
b[1, -3:]
b[:,-1]
#from this a single array of slicing
b[:,-2:-1]


array([[13],
       [ 9],
       [23]])

In [62]:
print(b[-1:,:])
print(c[:1, :2, :])
print(c[:, 1:2 ,:1])
print(c[-2:, -1:,:1])
print(c[:2,-2:,1:])


[[34 45 23 67]]
[[[ 10 100]
  [ 11 110]]]
[[[11]]

 [[56]]

 [[23]]]
[[[54]]

 [[78]]]
[[[45]
  [14]]

 [[ 9]
  [28]]]


In [1]:
c[:,:,-1:-2]

NameError: name 'c' is not defined

In [53]:
c

array([[[ 10, 100],
        [ 11, 110],
        [ 13,  45],
        [ 13,  14]],

       [[ 45,  67],
        [ 56,   6],
        [ 67,   9],
        [ 54,  28]],

       [[ 34,  78],
        [ 23,  45],
        [ 56,  23],
        [ 78,  67]]])

In [65]:
#Item assignment
b[1,2]=90
b

array([[10, 11, 13, 14],
       [45,  6, 90, 28],
       [34, 45, 23, 67]])

In [68]:
#Item Insertion
a = np.append(a,80)

In [69]:
a

array([ 3,  8,  2, 67, 45, 80])

In [72]:
np.append(b,[[9,90,900,90000]], axis=0) # axis =0 means row ,if 1 then column

array([[   10,    11,    13,    14],
       [   45,     6,    90,    28],
       [   34,    45,    23,    67],
       [    9,    90,   900, 90000]])

In [73]:
np.append(b,[[9],[90],[900]], axis=1)

array([[ 10,  11,  13,  14,   9],
       [ 45,   6,  90,  28,  90],
       [ 34,  45,  23,  67, 900]])

In [75]:
#Item Deletion
np.delete(b , 0, axis=0)

array([[45,  6, 90, 28],
       [34, 45, 23, 67]])

In [78]:
#arithmatic
a*2   #performs directly

array([  6,  16,   4, 134,  90, 160])

In [77]:
b*2

array([[ 20,  22,  26,  28],
       [ 90,  12, 180,  56],
       [ 68,  90,  46, 134]])

In [84]:
#Array manipulation
b.reshape(2,6,1)
#more functions to create array
#############################
## np.array
## np.arrange--> array version of range func,also allows float
##np.linspace()-->start,end,no. of itmes
##np.ones-->>generate all values as 1
##np.zeroes-->generate all alues as '0'
##np.random.random-->0.0 se 1.1
##np.random.randint-->

array([[[10],
        [11],
        [13],
        [14],
        [45],
        [ 6]],

       [[90],
        [28],
        [34],
        [45],
        [23],
        [67]]])

In [82]:
b.astype(float)

array([[10., 11., 13., 14.],
       [45.,  6., 90., 28.],
       [34., 45., 23., 67.]])

In [87]:
b.astype('uint16' )

array([[10, 11, 13, 14],
       [45,  6, 90, 28],
       [34, 45, 23, 67]], dtype=uint16)